// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxFgsMAXG6Uq8e6V7VRQotrG4OIPz93Ng',
    appId: '1:970168239081:web:4dea5acf961ea6a3524178',
    messagingSenderId: '970168239081',
    projectId: 'harvest-hub-9ccfb',
    authDomain: 'harvest-hub-9ccfb.firebaseapp.com',
    storageBucket: 'harvest-hub-9ccfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA571f5VXF5ZatEU4cV9kJJk1XAZ17LV7Q',
    appId: '1:970168239081:android:9b6079d15c0467bb524178',
    messagingSenderId: '970168239081',
    projectId: 'harvest-hub-9ccfb',
    storageBucket: 'harvest-hub-9ccfb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgKTdYgAJsDwV8TAmKW3IiCdLCK28os9Y',
    appId: '1:970168239081:ios:4400e737beade097524178',
    messagingSenderId: '970168239081',
    projectId: 'harvest-hub-9ccfb',
    storageBucket: 'harvest-hub-9ccfb.firebasestorage.app',
    iosBundleId: 'com.example.harvestHub',
  );
}
