import 'package:flutter/material.dart';
import '../models/user_model.dart';
import '../models/farmer_model.dart';
import '../models/product_model.dart';
import '../models/market_model.dart';
import '../models/customer_model.dart';
import '../models/category_model.dart';
import '../models/pickup_slot_model.dart';
import '../models/order_model.dart';
import '../models/notification_model.dart';
import '../models/cart_item_model.dart';
import '../models/review_model.dart';

class DummyData {
  static List<Map<String, dynamic>> categories = [
    {'id': '1', 'name': 'All', 'icon': Icons.apps, 'count': '48 items'},
    {'id': '2', 'name': 'Vegetables', 'icon': Icons.eco, 'count': '18 items'},
    {'id': '3', 'name': 'Fruits', 'icon': Icons.apple, 'count': '12 items'},
    {'id': '4', 'name': 'Dairy & Eggs', 'icon': Icons.water_drop, 'count': '8 items'},
    {'id': '5', 'name': 'Farm Honey', 'icon': Icons.hive, 'count': '5 items'},
    {'id': '6', 'name': 'Organic Herbs', 'icon': Icons.local_florist, 'count': '9 items'},
    {'id': '7', 'name': 'Cold Pressed Oils', 'icon': Icons.opacity, 'count': '4 items'},
    {'id': '8', 'name': 'Grains & Pulses', 'icon': Icons.grass, 'count': '11 items'},
    {'id': '9', 'name': 'Meat & Poultry', 'icon': Icons.set_meal, 'count': '6 items'},
  ];

  static List<Map<String, dynamic>> freshProducts = [
    {
      'id': 'p1',
      'title': 'Fresh Tomatoes',
      'category': 'VEGETABLES',
      'farmerName': 'Green Valley Farm',
      'price': '280',
      'unit': '/ kg',
      'stockBadge': '12 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFEF9A9A),
      'imageUrl': 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p2',
      'title': 'Organic Spinach',
      'category': 'VEGETABLES',
      'farmerName': 'Indus Organic Fi...',
      'price': '140',
      'unit': '/ bunch',
      'stockBadge': '8 bunches left',
      'isFavorite': true,
      'imageColor': Color(0xFFA5D6A7),
      'imageUrl': 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p3',
      'title': 'Fresh Carrots',
      'category': 'VEGETABLES',
      'farmerName': 'Sunny Side Farm',
      'price': '150',
      'unit': '/ kg',
      'stockBadge': '20 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFFFCC80),
      'imageUrl': 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p4',
      'title': 'Pure Farm Cow Milk',
      'category': 'DAIRY',
      'farmerName': 'Meadow Dairy F...',
      'price': '220',
      'unit': '/ L',
      'stockBadge': '15 L available',
      'isFavorite': false,
      'imageColor': Color(0xFFD7CCC8),
      'imageUrl': 'https://images.unsplash.com/photo-1563636619-e9143da7973b?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p5',
      'title': 'Raw Wildflower Honey',
      'category': 'ORGANIC',
      'farmerName': 'Mountain Bee A...',
      'price': '950',
      'unit': '/ jar',
      'stockBadge': '5 jars left',
      'isFavorite': false,
      'imageColor': Color(0xFFFFE082),
      'imageUrl': 'https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p6',
      'title': 'Juicy Apples',
      'category': 'FRUITS',
      'farmerName': 'Orchard Valley',
      'price': '400',
      'unit': '/ kg',
      'stockBadge': '30 kg available',
      'isFavorite': true,
      'imageColor': Color(0xFFEF5350),
      'imageUrl': 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p7',
      'title': 'Fresh Mint',
      'category': 'HERBS',
      'farmerName': 'Green Valley Farm',
      'price': '50',
      'unit': '/ bunch',
      'stockBadge': '40 bunches left',
      'isFavorite': false,
      'imageColor': Color(0xFF81C784),
    },
    {
      'id': 'p8',
      'title': 'Wheat Grains',
      'category': 'GRAINS',
      'farmerName': 'Golden Fields',
      'price': '120',
      'unit': '/ kg',
      'stockBadge': '500 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFFFB74D),
    },
    {
      'id': 'p9',
      'title': 'Red Onions',
      'category': 'VEGETABLES',
      'farmerName': 'Sindh Agri Co',
      'price': '180',
      'unit': '/ kg',
      'stockBadge': '50 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFCE93D8),
    },
    {
      'id': 'p10',
      'title': 'Potatoes',
      'category': 'VEGETABLES',
      'farmerName': 'Punjab Farms',
      'price': '120',
      'unit': '/ kg',
      'stockBadge': '100 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFBCAAA4),
    },
    {
      'id': 'p11',
      'title': 'Desi Eggs',
      'category': 'DAIRY',
      'farmerName': 'Ali Poultry Farm',
      'price': '450',
      'unit': '/ dozen',
      'stockBadge': '20 dozen left',
      'isFavorite': true,
      'imageColor': Color(0xFFFFF59D),
    },
    {
      'id': 'p12',
      'title': 'Pure Jaggery',
      'category': 'ORGANIC',
      'farmerName': 'Chaudhry Sugars',
      'price': '350',
      'unit': '/ kg',
      'stockBadge': '15 kg available',
      'isFavorite': true,
      'imageColor': Color(0xFF8D6E63),
    },
    {
      'id': 'p13',
      'title': 'Whole Wheat Atta',
      'category': 'GRAINS',
      'farmerName': 'Golden Fields',
      'price': '160',
      'unit': '/ kg',
      'stockBadge': '200 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFFFCC80),
    },
    {
      'id': 'p14',
      'title': 'Fresh Beef Gosht',
      'category': 'MEAT',
      'farmerName': 'Haji Cattle Farm',
      'price': '1200',
      'unit': '/ kg',
      'stockBadge': '30 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFE57373),
    },
    {
      'id': 'p15',
      'title': 'Raw Turmeric',
      'category': 'HERBS',
      'farmerName': 'Sindh Agri Co',
      'price': '400',
      'unit': '/ kg',
      'stockBadge': '10 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFFFB74D),
    },
    {
      'id': 'p16',
      'title': 'Mustard Oil',
      'category': 'OILS',
      'farmerName': 'Punjab Farms',
      'price': '600',
      'unit': '/ L',
      'stockBadge': '25 L available',
      'isFavorite': true,
      'imageColor': Color(0xFFFFF176),
    },
    {
      'id': 'p17',
      'title': 'Fresh Garlic',
      'category': 'VEGETABLES',
      'farmerName': 'Green Valley Farm',
      'price': '450',
      'unit': '/ kg',
      'stockBadge': '20 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFF5F5F5),
    },
    {
      'id': 'p18',
      'title': 'Ginger',
      'category': 'VEGETABLES',
      'farmerName': 'Sindh Agri Co',
      'price': '650',
      'unit': '/ kg',
      'stockBadge': '12 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFFFE082),
    },
    {
      'id': 'p19',
      'title': 'Desi Ghee',
      'category': 'DAIRY',
      'farmerName': 'Meadow Dairy F...',
      'price': '2200',
      'unit': '/ kg',
      'stockBadge': '5 kg left',
      'isFavorite': true,
      'imageColor': Color(0xFFFFF9C4),
    },
    {
      'id': 'p20',
      'title': 'Basmati Rice',
      'category': 'GRAINS',
      'farmerName': 'Golden Fields',
      'price': '380',
      'unit': '/ kg',
      'stockBadge': '100 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFF5F5F5),
    },
  ];

  static List<Map<String, dynamic>> popularFarmers = [
    {
      'id': 'f1',
      'name': 'Green Valley Farm',
      'rating': '4.8',
      'reviews': '120 reviews',
      'location': 'Karachi Farmers Market',
      'tags': 'Fresh Vegetables',
      'isFollowing': false,
    },
    {
      'id': 'f2',
      'name': 'Sunshine Organics',
      'rating': '4.9',
      'reviews': '95 reviews',
      'location': 'Clifton Organic Hub',
      'tags': 'Citrus Fruits',
      'isFollowing': true,
    },
    {
      'id': 'f3',
      'name': 'Sindh Agri Co',
      'rating': '4.6',
      'reviews': '200 reviews',
      'location': 'Malir Cantt Market',
      'tags': 'Root Vegetables',
      'isFollowing': false,
    },
    {
      'id': 'f4',
      'name': 'Punjab Farms',
      'rating': '4.7',
      'reviews': '150 reviews',
      'location': 'DHA Phase 8 Market',
      'tags': 'Grains and Oils',
      'isFollowing': true,
    },
    {
      'id': 'f5',
      'name': 'Ali Poultry Farm',
      'rating': '4.5',
      'reviews': '300 reviews',
      'location': 'Karachi Farmers Market',
      'tags': 'Eggs and Poultry',
      'isFollowing': false,
    },
    {
      'id': 'f6',
      'name': 'Meadow Dairy',
      'rating': '4.9',
      'reviews': '85 reviews',
      'location': 'Clifton Organic Hub',
      'tags': 'Pure Milk and Ghee',
      'isFollowing': true,
    },
    {
      'id': 'f7',
      'name': 'Chaudhry Sugars',
      'rating': '4.8',
      'reviews': '110 reviews',
      'location': 'Malir Cantt Market',
      'tags': 'Gur and Sugarcane',
      'isFollowing': false,
    },
    {
      'id': 'f8',
      'name': 'Haji Cattle Farm',
      'rating': '4.4',
      'reviews': '220 reviews',
      'location': 'Gulshan Weekly Bazaar',
      'tags': 'Fresh Meat',
      'isFollowing': false,
    },
  ];

  static List<Map<String, dynamic>> recentlyRestocked = [
    {
      'id': 'p4',
      'title': 'Pure Farm Cow Milk',
      'category': 'DAIRY',
      'farmerName': 'Meadow Dairy F...',
      'price': '220',
      'unit': '/ L',
      'stockBadge': '15 L available',
      'isFavorite': false,
      'imageColor': Color(0xFFD7CCC8),
      'imageUrl': 'https://images.unsplash.com/photo-1563636619-e9143da7973b?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p5',
      'title': 'Raw Wildflower Honey',
      'category': 'ORGANIC',
      'farmerName': 'Mountain Bee A...',
      'price': '950',
      'unit': '/ jar',
      'stockBadge': '5 jars left',
      'isFavorite': false,
      'imageColor': Color(0xFFFFE082),
      'imageUrl': 'https://images.unsplash.com/photo-1628151015968-3a4429e9ef04?q=80&w=400&auto=format&fit=crop',
    },
    {
      'id': 'p9',
      'title': 'Red Onions',
      'category': 'VEGETABLES',
      'farmerName': 'Sindh Agri Co',
      'price': '180',
      'unit': '/ kg',
      'stockBadge': '50 kg available',
      'isFavorite': false,
      'imageColor': Color(0xFFCE93D8),
    },
    {
      'id': 'p11',
      'title': 'Desi Eggs',
      'category': 'DAIRY',
      'farmerName': 'Ali Poultry Farm',
      'price': '450',
      'unit': '/ dozen',
      'stockBadge': '20 dozen left',
      'isFavorite': true,
      'imageColor': Color(0xFFFFF59D),
    },
    {
      'id': 'p19',
      'title': 'Desi Ghee',
      'category': 'DAIRY',
      'farmerName': 'Meadow Dairy F...',
      'price': '2200',
      'unit': '/ kg',
      'stockBadge': '5 kg left',
      'isFavorite': true,
      'imageColor': Color(0xFFFFF9C4),
    },
  ];

  static List<Map<String, dynamic>> cart = [];

  static List<Map<String, dynamic>> orders = [];

  static List<UserModel> seedUsers = [
    UserModel(uid: 'u1', name: 'Ali Raza', email: 'ali@example.com', role: 'Customer', phone: '03001234561', address: 'DHA Phase 1, Karachi', isActive: true, createdAt: DateTime(2026, 1, 1)),
    UserModel(uid: 'u2', name: 'Zainab Ahmed', email: 'zainab@example.com', role: 'Customer', phone: '03001234562', address: 'DHA Phase 2, Karachi', isActive: true, createdAt: DateTime(2026, 1, 2)),
    UserModel(uid: 'u3', name: 'Hassan Khan', email: 'hassan@example.com', role: 'Customer', phone: '03001234563', address: 'DHA Phase 3, Karachi', isActive: true, createdAt: DateTime(2026, 1, 3)),
    UserModel(uid: 'u4', name: 'Fatima Malik', email: 'fatima@example.com', role: 'Customer', phone: '03001234564', address: 'DHA Phase 4, Karachi', isActive: true, createdAt: DateTime(2026, 1, 4)),
    UserModel(uid: 'u5', name: 'Usman Ali', email: 'usman@example.com', role: 'Customer', phone: '03001234565', address: 'DHA Phase 5, Karachi', isActive: true, createdAt: DateTime(2026, 1, 5)),
    UserModel(uid: 'u6', name: 'Ayesha Tariq', email: 'ayesha@example.com', role: 'Customer', phone: '03001234566', address: 'DHA Phase 6, Karachi', isActive: true, createdAt: DateTime(2026, 1, 6)),
    UserModel(uid: 'u7', name: 'Bilal Hussain', email: 'bilal@example.com', role: 'Customer', phone: '03001234567', address: 'DHA Phase 7, Karachi', isActive: true, createdAt: DateTime(2026, 1, 7)),
    UserModel(uid: 'u8', name: 'Sara Shah', email: 'sara@example.com', role: 'Customer', phone: '03001234568', address: 'DHA Phase 8, Karachi', isActive: true, createdAt: DateTime(2026, 1, 8)),
    UserModel(uid: 'u9', name: 'Omar Farooq', email: 'omar@example.com', role: 'Customer', phone: '03001234569', address: 'Clifton Block 2, Karachi', isActive: true, createdAt: DateTime(2026, 1, 9)),
    UserModel(uid: 'u10', name: 'Sana Javed', email: 'sana@example.com', role: 'Customer', phone: '03001234560', address: 'Clifton Block 4, Karachi', isActive: true, createdAt: DateTime(2026, 1, 10)),
    UserModel(uid: 'u11', name: 'Farmer Ali', email: 'farmer11@example.com', role: 'Farmer', phone: '03111223341', address: 'Malir Farms 1, Karachi', isActive: true, createdAt: DateTime(2026, 2, 1)),
    UserModel(uid: 'u12', name: 'Farmer Zain', email: 'farmer12@example.com', role: 'Farmer', phone: '03111223342', address: 'Malir Farms 2, Karachi', isActive: true, createdAt: DateTime(2026, 2, 2)),
    UserModel(uid: 'u13', name: 'Farmer Qasim', email: 'farmer13@example.com', role: 'Farmer', phone: '03111223343', address: 'Malir Farms 3, Karachi', isActive: true, createdAt: DateTime(2026, 2, 3)),
    UserModel(uid: 'u14', name: 'Farmer Tariq', email: 'farmer14@example.com', role: 'Farmer', phone: '03111223344', address: 'Malir Farms 4, Karachi', isActive: true, createdAt: DateTime(2026, 2, 4)),
    UserModel(uid: 'u15', name: 'Farmer Bilal', email: 'farmer15@example.com', role: 'Farmer', phone: '03111223345', address: 'Malir Farms 5, Karachi', isActive: true, createdAt: DateTime(2026, 2, 5)),
    UserModel(uid: 'u16', name: 'Farmer Dawood', email: 'farmer16@example.com', role: 'Farmer', phone: '03111223346', address: 'Malir Farms 6, Karachi', isActive: true, createdAt: DateTime(2026, 2, 6)),
    UserModel(uid: 'u17', name: 'Farmer Raza', email: 'farmer17@example.com', role: 'Farmer', phone: '03111223347', address: 'Malir Farms 7, Karachi', isActive: true, createdAt: DateTime(2026, 2, 7)),
    UserModel(uid: 'u18', name: 'Farmer Yasir', email: 'farmer18@example.com', role: 'Farmer', phone: '03111223348', address: 'Malir Farms 8, Karachi', isActive: true, createdAt: DateTime(2026, 2, 8)),
    UserModel(uid: 'u19', name: 'Admin Sameer', email: 'admin19@example.com', role: 'Admin', phone: '03339988779', address: 'Admin House 1, Karachi', isActive: true, createdAt: DateTime(2026, 3, 1)),
    UserModel(uid: 'u20', name: 'Admin Nida', email: 'admin20@example.com', role: 'Admin', phone: '03339988770', address: 'Admin House 2, Karachi', isActive: true, createdAt: DateTime(2026, 3, 2)),
  ];

  static List<CustomerModel> seedCustomers = [
    CustomerModel(id: 'c1', userId: 'u1', name: 'Ali Raza', email: 'ali@example.com', phone: '03001234561', address: 'DHA Phase 1, Karachi', wishlist: ['p1', 'p2'], followedFarmers: ['f1', 'f2'], createdAt: DateTime(2026, 1, 1)),
    CustomerModel(id: 'c2', userId: 'u2', name: 'Zainab Ahmed', email: 'zainab@example.com', phone: '03001234562', address: 'DHA Phase 2, Karachi', wishlist: ['p3', 'p4'], followedFarmers: ['f3', 'f4'], createdAt: DateTime(2026, 1, 2)),
    CustomerModel(id: 'c3', userId: 'u3', name: 'Hassan Khan', email: 'hassan@example.com', phone: '03001234563', address: 'DHA Phase 3, Karachi', wishlist: ['p5', 'p6'], followedFarmers: ['f5', 'f6'], createdAt: DateTime(2026, 1, 3)),
    CustomerModel(id: 'c4', userId: 'u4', name: 'Fatima Malik', email: 'fatima@example.com', phone: '03001234564', address: 'DHA Phase 4, Karachi', wishlist: ['p7', 'p8'], followedFarmers: ['f7', 'f8'], createdAt: DateTime(2026, 1, 4)),
    CustomerModel(id: 'c5', userId: 'u5', name: 'Usman Ali', email: 'usman@example.com', phone: '03001234565', address: 'DHA Phase 5, Karachi', wishlist: ['p9', 'p10'], followedFarmers: ['f1', 'f3'], createdAt: DateTime(2026, 1, 5)),
    CustomerModel(id: 'c6', userId: 'u6', name: 'Ayesha Tariq', email: 'ayesha@example.com', phone: '03001234566', address: 'DHA Phase 6, Karachi', wishlist: ['p11', 'p12'], followedFarmers: ['f2', 'f4'], createdAt: DateTime(2026, 1, 6)),
    CustomerModel(id: 'c7', userId: 'u7', name: 'Bilal Hussain', email: 'bilal@example.com', phone: '03001234567', address: 'DHA Phase 7, Karachi', wishlist: ['p13', 'p14'], followedFarmers: ['f5', 'f7'], createdAt: DateTime(2026, 1, 7)),
    CustomerModel(id: 'c8', userId: 'u8', name: 'Sara Shah', email: 'sara@example.com', phone: '03001234568', address: 'DHA Phase 8, Karachi', wishlist: ['p15', 'p16'], followedFarmers: ['f6', 'f8'], createdAt: DateTime(2026, 1, 8)),
    CustomerModel(id: 'c9', userId: 'u9', name: 'Omar Farooq', email: 'omar@example.com', phone: '03001234569', address: 'Clifton Block 2, Karachi', wishlist: ['p17', 'p18'], followedFarmers: ['f1', 'f5'], createdAt: DateTime(2026, 1, 9)),
    CustomerModel(id: 'c10', userId: 'u10', name: 'Sana Javed', email: 'sana@example.com', phone: '03001234560', address: 'Clifton Block 4, Karachi', wishlist: ['p19', 'p20'], followedFarmers: ['f2', 'f6'], createdAt: DateTime(2026, 1, 10)),
  ];

  static List<MarketModel> seedMarkets = [
    MarketModel(id: 'm1', name: 'Karachi Farmers Market', address: 'Main Khayaban-e-Ittehad, DHA', gpsCoordinates: '24.8103, 67.0543', operatingHours: 'Sun: 8:00 AM - 1:00 PM', activeStatus: true, description: 'The largest weekly farmers market in Karachi.'),
    MarketModel(id: 'm2', name: 'Clifton Organic Hub', address: 'Clifton Block 4 Park', gpsCoordinates: '24.8214, 67.0311', operatingHours: 'Sat: 9:00 AM - 2:00 PM', activeStatus: true, description: 'Premium organic produce.'),
    MarketModel(id: 'm3', name: 'Malir Cantt Market', address: 'Cantt Bazaar Area', gpsCoordinates: '24.9351, 67.1952', operatingHours: 'Fri: 7:00 AM - 12:00 PM', activeStatus: true, description: 'Fresh farm arrivals every Friday.'),
    MarketModel(id: 'm4', name: 'DHA Phase 8 Market', address: 'Creek Club Road', gpsCoordinates: '24.7901, 67.0712', operatingHours: 'Sun: 4:00 PM - 9:00 PM', activeStatus: true, description: 'Evening organic market by the sea.'),
    MarketModel(id: 'm5', name: 'Gulshan Weekly Bazaar', address: 'Gulshan Block 13-C', gpsCoordinates: '24.9192, 67.0984', operatingHours: 'Tue: 8:00 AM - 5:00 PM', activeStatus: true, description: 'Affordable wholesale farmers market.'),
  ];

  static List<FarmerModel> seedFarmers = [
    FarmerModel(id: 'f1', userId: 'u11', farmName: 'Green Valley Farm', description: 'Fresh produce from Green Valley Farm.', location: 'Karachi Region', contactNumber: '03111223341', marketId: 'm1', rating: 4.8, isApproved: true, createdAt: DateTime(2026, 2, 1)),
    FarmerModel(id: 'f2', userId: 'u12', farmName: 'Sunshine Organics', description: 'Fresh produce from Sunshine Organics.', location: 'Karachi Region', contactNumber: '03111223342', marketId: 'm2', rating: 4.9, isApproved: true, createdAt: DateTime(2026, 2, 2)),
    FarmerModel(id: 'f3', userId: 'u13', farmName: 'Sindh Agri Co', description: 'Fresh produce from Sindh Agri Co.', location: 'Karachi Region', contactNumber: '03111223343', marketId: 'm3', rating: 4.6, isApproved: true, createdAt: DateTime(2026, 2, 3)),
    FarmerModel(id: 'f4', userId: 'u14', farmName: 'Punjab Farms', description: 'Fresh produce from Punjab Farms.', location: 'Karachi Region', contactNumber: '03111223344', marketId: 'm4', rating: 4.7, isApproved: true, createdAt: DateTime(2026, 2, 4)),
    FarmerModel(id: 'f5', userId: 'u15', farmName: 'Ali Poultry Farm', description: 'Fresh produce from Ali Poultry Farm.', location: 'Karachi Region', contactNumber: '03111223345', marketId: 'm5', rating: 4.5, isApproved: false, createdAt: DateTime(2026, 2, 5)),
    FarmerModel(id: 'f6', userId: 'u16', farmName: 'Meadow Dairy', description: 'Fresh produce from Meadow Dairy.', location: 'Karachi Region', contactNumber: '03111223346', marketId: 'm1', rating: 4.9, isApproved: true, createdAt: DateTime(2026, 2, 6)),
    FarmerModel(id: 'f7', userId: 'u17', farmName: 'Chaudhry Sugars', description: 'Fresh produce from Chaudhry Sugars.', location: 'Karachi Region', contactNumber: '03111223347', marketId: 'm2', rating: 4.8, isApproved: true, createdAt: DateTime(2026, 2, 7)),
    FarmerModel(id: 'f8', userId: 'u18', farmName: 'Haji Cattle Farm', description: 'Fresh produce from Haji Cattle Farm.', location: 'Karachi Region', contactNumber: '03111223348', marketId: 'm3', rating: 4.4, isApproved: false, createdAt: DateTime(2026, 2, 8)),
  ];

  static List<ProductModel> seedProducts = [
    ProductModel(id: 'p1', farmerId: 'f1', categoryId: '2', categoryName: 'Vegetables', name: 'Fresh Tomatoes', description: 'Quality Fresh Tomatoes fresh from the farm.', price: 280, unit: 'kg', quantity: 12, isAvailable: true, farmerName: 'Green Valley Farm', createdAt: DateTime(2026, 4, 1)),
    ProductModel(id: 'p2', farmerId: 'f1', categoryId: '2', categoryName: 'Vegetables', name: 'Organic Spinach', description: 'Quality Organic Spinach fresh from the farm.', price: 140, unit: 'bunch', quantity: 8, isAvailable: true, farmerName: 'Green Valley Farm', createdAt: DateTime(2026, 4, 2)),
    ProductModel(id: 'p3', farmerId: 'f1', categoryId: '2', categoryName: 'Vegetables', name: 'Fresh Carrots', description: 'Quality Fresh Carrots fresh from the farm.', price: 150, unit: 'kg', quantity: 20, isAvailable: true, farmerName: 'Green Valley Farm', createdAt: DateTime(2026, 4, 3)),
    ProductModel(id: 'p4', farmerId: 'f6', categoryId: '4', categoryName: 'Dairy & Eggs', name: 'Pure Farm Cow Milk', description: 'Quality Pure Farm Cow Milk fresh from the farm.', price: 220, unit: 'L', quantity: 15, isAvailable: true, farmerName: 'Meadow Dairy', createdAt: DateTime(2026, 4, 4)),
    ProductModel(id: 'p5', farmerId: 'f2', categoryId: '5', categoryName: 'Farm Honey', name: 'Raw Wildflower Honey', description: 'Quality Raw Wildflower Honey fresh from the farm.', price: 950, unit: 'jar', quantity: 5, isAvailable: true, farmerName: 'Sunshine Organics', createdAt: DateTime(2026, 4, 5)),
    ProductModel(id: 'p6', farmerId: 'f2', categoryId: '3', categoryName: 'Fruits', name: 'Juicy Apples', description: 'Quality Juicy Apples fresh from the farm.', price: 400, unit: 'kg', quantity: 30, isAvailable: true, farmerName: 'Sunshine Organics', createdAt: DateTime(2026, 4, 6)),
    ProductModel(id: 'p7', farmerId: 'f1', categoryId: '6', categoryName: 'Organic Herbs', name: 'Fresh Mint', description: 'Quality Fresh Mint fresh from the farm.', price: 50, unit: 'bunch', quantity: 40, isAvailable: true, farmerName: 'Green Valley Farm', createdAt: DateTime(2026, 4, 7)),
    ProductModel(id: 'p8', farmerId: 'f4', categoryId: '8', categoryName: 'Grains & Pulses', name: 'Wheat Grains', description: 'Quality Wheat Grains fresh from the farm.', price: 120, unit: 'kg', quantity: 500, isAvailable: true, farmerName: 'Punjab Farms', createdAt: DateTime(2026, 4, 8)),
    ProductModel(id: 'p9', farmerId: 'f3', categoryId: '2', categoryName: 'Vegetables', name: 'Red Onions', description: 'Quality Red Onions fresh from the farm.', price: 180, unit: 'kg', quantity: 50, isAvailable: true, farmerName: 'Sindh Agri Co', createdAt: DateTime(2026, 4, 9)),
    ProductModel(id: 'p10', farmerId: 'f4', categoryId: '2', categoryName: 'Vegetables', name: 'Potatoes', description: 'Quality Potatoes fresh from the farm.', price: 120, unit: 'kg', quantity: 100, isAvailable: true, farmerName: 'Punjab Farms', createdAt: DateTime(2026, 4, 10)),
    ProductModel(id: 'p11', farmerId: 'f5', categoryId: '4', categoryName: 'Dairy & Eggs', name: 'Desi Eggs', description: 'Quality Desi Eggs fresh from the farm.', price: 450, unit: 'dozen', quantity: 20, isAvailable: true, farmerName: 'Ali Poultry Farm', createdAt: DateTime(2026, 4, 11)),
    ProductModel(id: 'p12', farmerId: 'f7', categoryId: '5', categoryName: 'Farm Honey', name: 'Pure Jaggery', description: 'Quality Pure Jaggery fresh from the farm.', price: 350, unit: 'kg', quantity: 15, isAvailable: true, farmerName: 'Chaudhry Sugars', createdAt: DateTime(2026, 4, 12)),
    ProductModel(id: 'p13', farmerId: 'f4', categoryId: '8', categoryName: 'Grains & Pulses', name: 'Whole Wheat Atta', description: 'Quality Whole Wheat Atta fresh from the farm.', price: 160, unit: 'kg', quantity: 200, isAvailable: true, farmerName: 'Punjab Farms', createdAt: DateTime(2026, 4, 13)),
    ProductModel(id: 'p14', farmerId: 'f8', categoryId: '9', categoryName: 'Meat & Poultry', name: 'Fresh Beef Gosht', description: 'Quality Fresh Beef Gosht fresh from the farm.', price: 1200, unit: 'kg', quantity: 30, isAvailable: true, farmerName: 'Haji Cattle Farm', createdAt: DateTime(2026, 4, 14)),
    ProductModel(id: 'p15', farmerId: 'f3', categoryId: '6', categoryName: 'Organic Herbs', name: 'Raw Turmeric', description: 'Quality Raw Turmeric fresh from the farm.', price: 400, unit: 'kg', quantity: 10, isAvailable: true, farmerName: 'Sindh Agri Co', createdAt: DateTime(2026, 4, 15)),
    ProductModel(id: 'p16', farmerId: 'f4', categoryId: '7', categoryName: 'Cold Pressed Oils', name: 'Mustard Oil', description: 'Quality Mustard Oil fresh from the farm.', price: 600, unit: 'L', quantity: 25, isAvailable: true, farmerName: 'Punjab Farms', createdAt: DateTime(2026, 4, 16)),
    ProductModel(id: 'p17', farmerId: 'f1', categoryId: '2', categoryName: 'Vegetables', name: 'Fresh Garlic', description: 'Quality Fresh Garlic fresh from the farm.', price: 450, unit: 'kg', quantity: 20, isAvailable: true, farmerName: 'Green Valley Farm', createdAt: DateTime(2026, 4, 17)),
    ProductModel(id: 'p18', farmerId: 'f3', categoryId: '2', categoryName: 'Vegetables', name: 'Ginger', description: 'Quality Ginger fresh from the farm.', price: 650, unit: 'kg', quantity: 12, isAvailable: true, farmerName: 'Sindh Agri Co', createdAt: DateTime(2026, 4, 18)),
    ProductModel(id: 'p19', farmerId: 'f6', categoryId: '4', categoryName: 'Dairy & Eggs', name: 'Desi Ghee', description: 'Quality Desi Ghee fresh from the farm.', price: 2200, unit: 'kg', quantity: 5, isAvailable: true, farmerName: 'Meadow Dairy', createdAt: DateTime(2026, 4, 19)),
    ProductModel(id: 'p20', farmerId: 'f4', categoryId: '8', categoryName: 'Grains & Pulses', name: 'Basmati Rice', description: 'Quality Basmati Rice fresh from the farm.', price: 380, unit: 'kg', quantity: 100, isAvailable: true, farmerName: 'Punjab Farms', createdAt: DateTime(2026, 4, 20)),
  ];

  static List<CategoryModel> seedCategories = [
    CategoryModel(id: '1', name: 'All', iconName: 'apps', itemCount: '48 items'),
    CategoryModel(id: '2', name: 'Vegetables', iconName: 'eco', itemCount: '18 items'),
    CategoryModel(id: '3', name: 'Fruits', iconName: 'apple', itemCount: '12 items'),
    CategoryModel(id: '4', name: 'Dairy & Eggs', iconName: 'water_drop', itemCount: '8 items'),
    CategoryModel(id: '5', name: 'Farm Honey', iconName: 'hive', itemCount: '5 items'),
    CategoryModel(id: '6', name: 'Organic Herbs', iconName: 'local_florist', itemCount: '9 items'),
    CategoryModel(id: '7', name: 'Cold Pressed Oils', iconName: 'opacity', itemCount: '4 items'),
    CategoryModel(id: '8', name: 'Grains & Pulses', iconName: 'grass', itemCount: '11 items'),
    CategoryModel(id: '9', name: 'Meat & Poultry', iconName: 'set_meal', itemCount: '6 items'),
  ];

  static List<PickupSlotModel> seedPickupSlots = [
    PickupSlotModel(id: 'ps1', marketId: 'm1', farmerId: 'f1', date: '2026-10-15', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 10, currentBookings: 2),
    PickupSlotModel(id: 'ps2', marketId: 'm2', farmerId: 'f2', date: '2026-10-16', startTime: '10:00 AM', endTime: '12:00 PM', isAvailable: true, maxBookings: 10, currentBookings: 5),
    PickupSlotModel(id: 'ps3', marketId: 'm3', farmerId: 'f3', date: '2026-10-17', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 12, currentBookings: 8),
    PickupSlotModel(id: 'ps4', marketId: 'm4', farmerId: 'f4', date: '2026-10-18', startTime: '04:00 PM', endTime: '06:00 PM', isAvailable: true, maxBookings: 15, currentBookings: 15),
    PickupSlotModel(id: 'ps5', marketId: 'm5', farmerId: 'f5', date: '2026-10-19', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 8, currentBookings: 2),
    PickupSlotModel(id: 'ps6', marketId: 'm1', farmerId: 'f6', date: '2026-10-20', startTime: '10:00 AM', endTime: '12:00 PM', isAvailable: true, maxBookings: 5, currentBookings: 1),
    PickupSlotModel(id: 'ps7', marketId: 'm2', farmerId: 'f7', date: '2026-10-21', startTime: '12:00 PM', endTime: '02:00 PM', isAvailable: true, maxBookings: 10, currentBookings: 4),
    PickupSlotModel(id: 'ps8', marketId: 'm3', farmerId: 'f8', date: '2026-10-22', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 14, currentBookings: 10),
    PickupSlotModel(id: 'ps9', marketId: 'm4', farmerId: 'f1', date: '2026-10-23', startTime: '04:00 PM', endTime: '06:00 PM', isAvailable: true, maxBookings: 10, currentBookings: 0),
    PickupSlotModel(id: 'ps10', marketId: 'm5', farmerId: 'f2', date: '2026-10-24', startTime: '10:00 AM', endTime: '12:00 PM', isAvailable: true, maxBookings: 6, currentBookings: 2),
    PickupSlotModel(id: 'ps11', marketId: 'm1', farmerId: 'f3', date: '2026-10-25', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 10, currentBookings: 7),
    PickupSlotModel(id: 'ps12', marketId: 'm2', farmerId: 'f4', date: '2026-10-26', startTime: '10:00 AM', endTime: '12:00 PM', isAvailable: true, maxBookings: 12, currentBookings: 11),
    PickupSlotModel(id: 'ps13', marketId: 'm3', farmerId: 'f5', date: '2026-10-27', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 15, currentBookings: 3),
    PickupSlotModel(id: 'ps14', marketId: 'm4', farmerId: 'f6', date: '2026-10-28', startTime: '04:00 PM', endTime: '06:00 PM', isAvailable: true, maxBookings: 5, currentBookings: 5),
    PickupSlotModel(id: 'ps15', marketId: 'm5', farmerId: 'f7', date: '2026-10-29', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 10, currentBookings: 1),
    PickupSlotModel(id: 'ps16', marketId: 'm1', farmerId: 'f8', date: '2026-10-30', startTime: '10:00 AM', endTime: '12:00 PM', isAvailable: true, maxBookings: 10, currentBookings: 6),
    PickupSlotModel(id: 'ps17', marketId: 'm2', farmerId: 'f1', date: '2026-10-31', startTime: '12:00 PM', endTime: '02:00 PM', isAvailable: true, maxBookings: 8, currentBookings: 8),
    PickupSlotModel(id: 'ps18', marketId: 'm3', farmerId: 'f2', date: '2026-11-01', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 10, currentBookings: 4),
    PickupSlotModel(id: 'ps19', marketId: 'm4', farmerId: 'f3', date: '2026-11-02', startTime: '04:00 PM', endTime: '06:00 PM', isAvailable: true, maxBookings: 10, currentBookings: 0),
    PickupSlotModel(id: 'ps20', marketId: 'm5', farmerId: 'f4', date: '2026-11-03', startTime: '08:00 AM', endTime: '10:00 AM', isAvailable: true, maxBookings: 15, currentBookings: 10),
  ];

  static List<OrderModel> seedOrders = [
    OrderModel(id: 'o1', customerId: 'c1', customerName: 'Ali Raza', customerPhone: '03001234561', farmerId: 'f1', items: [OrderItem(productId: 'p1', farmerId: 'f1', productName: 'Fresh Tomatoes', price: 280, quantity: 2, unit: 'kg')], totalAmount: 560, pickupSlotId: 'ps1', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm1', status: 'Pending', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 20)),
    OrderModel(id: 'o2', customerId: 'c2', customerName: 'Zainab Ahmed', customerPhone: '03001234562', farmerId: 'f2', items: [OrderItem(productId: 'p2', farmerId: 'f2', productName: 'Organic Spinach', price: 140, quantity: 3, unit: 'bunch')], totalAmount: 420, pickupSlotId: 'ps2', pickupSlotTime: '10:00 AM - 12:00 PM', marketId: 'm2', status: 'Confirmed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 21)),
    OrderModel(id: 'o3', customerId: 'c3', customerName: 'Hassan Khan', customerPhone: '03001234563', farmerId: 'f3', items: [OrderItem(productId: 'p3', farmerId: 'f3', productName: 'Fresh Carrots', price: 150, quantity: 1, unit: 'kg')], totalAmount: 150, pickupSlotId: 'ps3', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm3', status: 'Ready for Pickup', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 22)),
    OrderModel(id: 'o4', customerId: 'c4', customerName: 'Fatima Malik', customerPhone: '03001234564', farmerId: 'f4', items: [OrderItem(productId: 'p4', farmerId: 'f4', productName: 'Pure Farm Cow Milk', price: 220, quantity: 5, unit: 'L')], totalAmount: 1100, pickupSlotId: 'ps4', pickupSlotTime: '04:00 PM - 06:00 PM', marketId: 'm4', status: 'Completed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 23)),
    OrderModel(id: 'o5', customerId: 'c5', customerName: 'Usman Ali', customerPhone: '03001234565', farmerId: 'f5', items: [OrderItem(productId: 'p5', farmerId: 'f5', productName: 'Raw Wildflower Honey', price: 950, quantity: 2, unit: 'jar')], totalAmount: 1900, pickupSlotId: 'ps5', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm5', status: 'Cancelled', cancellationReason: 'Customer changed mind', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 24)),
    OrderModel(id: 'o6', customerId: 'c6', customerName: 'Ayesha Tariq', customerPhone: '03001234566', farmerId: 'f6', items: [OrderItem(productId: 'p6', farmerId: 'f6', productName: 'Juicy Apples', price: 400, quantity: 2, unit: 'kg')], totalAmount: 800, pickupSlotId: 'ps6', pickupSlotTime: '10:00 AM - 12:00 PM', marketId: 'm1', status: 'Pending', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 25)),
    OrderModel(id: 'o7', customerId: 'c7', customerName: 'Bilal Hussain', customerPhone: '03001234567', farmerId: 'f7', items: [OrderItem(productId: 'p7', farmerId: 'f7', productName: 'Fresh Mint', price: 50, quantity: 4, unit: 'bunch')], totalAmount: 200, pickupSlotId: 'ps7', pickupSlotTime: '12:00 PM - 02:00 PM', marketId: 'm2', status: 'Confirmed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 26)),
    OrderModel(id: 'o8', customerId: 'c8', customerName: 'Sara Shah', customerPhone: '03001234568', farmerId: 'f8', items: [OrderItem(productId: 'p8', farmerId: 'f8', productName: 'Wheat Grains', price: 120, quantity: 10, unit: 'kg')], totalAmount: 1200, pickupSlotId: 'ps8', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm3', status: 'Ready for Pickup', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 27)),
    OrderModel(id: 'o9', customerId: 'c9', customerName: 'Omar Farooq', customerPhone: '03001234569', farmerId: 'f1', items: [OrderItem(productId: 'p9', farmerId: 'f1', productName: 'Red Onions', price: 180, quantity: 3, unit: 'kg')], totalAmount: 540, pickupSlotId: 'ps9', pickupSlotTime: '04:00 PM - 06:00 PM', marketId: 'm4', status: 'Completed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 28)),
    OrderModel(id: 'o10', customerId: 'c10', customerName: 'Sana Javed', customerPhone: '03001234560', farmerId: 'f2', items: [OrderItem(productId: 'p10', farmerId: 'f2', productName: 'Potatoes', price: 120, quantity: 5, unit: 'kg')], totalAmount: 600, pickupSlotId: 'ps10', pickupSlotTime: '10:00 AM - 12:00 PM', marketId: 'm5', status: 'Cancelled', cancellationReason: 'Stock unavailable', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 28)),
    OrderModel(id: 'o11', customerId: 'c1', customerName: 'Ali Raza', customerPhone: '03001234561', farmerId: 'f3', items: [OrderItem(productId: 'p11', farmerId: 'f3', productName: 'Desi Eggs', price: 450, quantity: 2, unit: 'dozen')], totalAmount: 900, pickupSlotId: 'ps11', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm1', status: 'Pending', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 20)),
    OrderModel(id: 'o12', customerId: 'c2', customerName: 'Zainab Ahmed', customerPhone: '03001234562', farmerId: 'f4', items: [OrderItem(productId: 'p12', farmerId: 'f4', productName: 'Pure Jaggery', price: 350, quantity: 1, unit: 'kg')], totalAmount: 350, pickupSlotId: 'ps12', pickupSlotTime: '10:00 AM - 12:00 PM', marketId: 'm2', status: 'Confirmed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 21)),
    OrderModel(id: 'o13', customerId: 'c3', customerName: 'Hassan Khan', customerPhone: '03001234563', farmerId: 'f5', items: [OrderItem(productId: 'p13', farmerId: 'f5', productName: 'Whole Wheat Atta', price: 160, quantity: 10, unit: 'kg')], totalAmount: 1600, pickupSlotId: 'ps13', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm3', status: 'Ready for Pickup', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 22)),
    OrderModel(id: 'o14', customerId: 'c4', customerName: 'Fatima Malik', customerPhone: '03001234564', farmerId: 'f6', items: [OrderItem(productId: 'p14', farmerId: 'f6', productName: 'Fresh Beef Gosht', price: 1200, quantity: 2, unit: 'kg')], totalAmount: 2400, pickupSlotId: 'ps14', pickupSlotTime: '04:00 PM - 06:00 PM', marketId: 'm4', status: 'Completed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 23)),
    OrderModel(id: 'o15', customerId: 'c5', customerName: 'Usman Ali', customerPhone: '03001234565', farmerId: 'f7', items: [OrderItem(productId: 'p15', farmerId: 'f7', productName: 'Raw Turmeric', price: 400, quantity: 1, unit: 'kg')], totalAmount: 400, pickupSlotId: 'ps15', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm5', status: 'Pending', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 24)),
    OrderModel(id: 'o16', customerId: 'c6', customerName: 'Ayesha Tariq', customerPhone: '03001234566', farmerId: 'f8', items: [OrderItem(productId: 'p16', farmerId: 'f8', productName: 'Mustard Oil', price: 600, quantity: 3, unit: 'L')], totalAmount: 1800, pickupSlotId: 'ps16', pickupSlotTime: '10:00 AM - 12:00 PM', marketId: 'm1', status: 'Confirmed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 25)),
    OrderModel(id: 'o17', customerId: 'c7', customerName: 'Bilal Hussain', customerPhone: '03001234567', farmerId: 'f1', items: [OrderItem(productId: 'p17', farmerId: 'f1', productName: 'Fresh Garlic', price: 450, quantity: 2, unit: 'kg')], totalAmount: 900, pickupSlotId: 'ps17', pickupSlotTime: '12:00 PM - 02:00 PM', marketId: 'm2', status: 'Ready for Pickup', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 26)),
    OrderModel(id: 'o18', customerId: 'c8', customerName: 'Sara Shah', customerPhone: '03001234568', farmerId: 'f2', items: [OrderItem(productId: 'p18', farmerId: 'f2', productName: 'Ginger', price: 650, quantity: 1, unit: 'kg')], totalAmount: 650, pickupSlotId: 'ps18', pickupSlotTime: '08:00 AM - 10:00 AM', marketId: 'm3', status: 'Completed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 27)),
    OrderModel(id: 'o19', customerId: 'c9', customerName: 'Omar Farooq', customerPhone: '03001234569', farmerId: 'f3', items: [OrderItem(productId: 'p19', farmerId: 'f3', productName: 'Desi Ghee', price: 2200, quantity: 2, unit: 'kg')], totalAmount: 4400, pickupSlotId: 'ps19', pickupSlotTime: '04:00 PM - 06:00 PM', marketId: 'm4', status: 'Pending', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 28)),
    OrderModel(id: 'o20', customerId: 'c10', customerName: 'Sana Javed', customerPhone: '03001234560', farmerId: 'f4', items: [OrderItem(productId: 'p20', farmerId: 'f4', productName: 'Basmati Rice', price: 380, quantity: 5, unit: 'kg')], totalAmount: 1900, pickupSlotId: 'ps20', pickupSlotTime: '10:00 AM - 12:00 PM', marketId: 'm5', status: 'Confirmed', paymentMethod: 'Cash on Pickup', createdAt: DateTime(2026, 9, 28)),
  ];

  static List<NotificationModel> seedNotifications = [];

  static List<ReviewModel> seedReviews = [
    ReviewModel(id: 'r1', customerId: 'c1', customerName: 'Ali Raza', targetId: 'f1', targetType: 'farmer', rating: 4.5, comment: 'Excellent quality and fresh.', createdAt: DateTime(2026, 8, 1)),
    ReviewModel(id: 'r2', customerId: 'c2', customerName: 'Zainab Ahmed', targetId: 'p2', targetType: 'product', rating: 5.0, comment: 'Very green and healthy spinach.', createdAt: DateTime(2026, 8, 2)),
    ReviewModel(id: 'r3', customerId: 'c3', customerName: 'Hassan Khan', targetId: 'f3', targetType: 'farmer', rating: 4.0, comment: 'Good farmer, nice attitude.', createdAt: DateTime(2026, 8, 3)),
    ReviewModel(id: 'r4', customerId: 'c4', customerName: 'Fatima Malik', targetId: 'p4', targetType: 'product', rating: 4.8, comment: 'Real pure milk.', createdAt: DateTime(2026, 8, 4)),
    ReviewModel(id: 'r5', customerId: 'c5', customerName: 'Usman Ali', targetId: 'f5', targetType: 'farmer', rating: 4.2, comment: 'On time delivery.', createdAt: DateTime(2026, 8, 5)),
    ReviewModel(id: 'r6', customerId: 'c6', customerName: 'Ayesha Tariq', targetId: 'p6', targetType: 'product', rating: 4.9, comment: 'Sweetest apples.', createdAt: DateTime(2026, 8, 6)),
    ReviewModel(id: 'r7', customerId: 'c7', customerName: 'Bilal Hussain', targetId: 'f7', targetType: 'farmer', rating: 4.7, comment: 'Very clean produce.', createdAt: DateTime(2026, 8, 7)),
    ReviewModel(id: 'r8', customerId: 'c8', customerName: 'Sara Shah', targetId: 'p8', targetType: 'product', rating: 4.1, comment: 'Clean wheat.', createdAt: DateTime(2026, 8, 8)),
    ReviewModel(id: 'r9', customerId: 'c9', customerName: 'Omar Farooq', targetId: 'f1', targetType: 'farmer', rating: 5.0, comment: 'My favorite farmer in Karachi.', createdAt: DateTime(2026, 8, 9)),
    ReviewModel(id: 'r10', customerId: 'c10', customerName: 'Sana Javed', targetId: 'p10', targetType: 'product', rating: 4.5, comment: 'Good size potatoes.', createdAt: DateTime(2026, 8, 10)),
    ReviewModel(id: 'r11', customerId: 'c1', customerName: 'Ali Raza', targetId: 'f3', targetType: 'farmer', rating: 4.6, comment: 'Highly recommended.', createdAt: DateTime(2026, 8, 11)),
    ReviewModel(id: 'r12', customerId: 'c2', customerName: 'Zainab Ahmed', targetId: 'p12', targetType: 'product', rating: 4.8, comment: 'Very sweet jaggery.', createdAt: DateTime(2026, 8, 12)),
    ReviewModel(id: 'r13', customerId: 'c3', customerName: 'Hassan Khan', targetId: 'f5', targetType: 'farmer', rating: 4.3, comment: 'Fresh eggs always.', createdAt: DateTime(2026, 8, 13)),
    ReviewModel(id: 'r14', customerId: 'c4', customerName: 'Fatima Malik', targetId: 'p14', targetType: 'product', rating: 4.9, comment: 'Tender beef.', createdAt: DateTime(2026, 8, 14)),
    ReviewModel(id: 'r15', customerId: 'c5', customerName: 'Usman Ali', targetId: 'f7', targetType: 'farmer', rating: 4.7, comment: 'Best sugar products.', createdAt: DateTime(2026, 8, 15)),
    ReviewModel(id: 'r16', customerId: 'c6', customerName: 'Ayesha Tariq', targetId: 'p16', targetType: 'product', rating: 4.4, comment: 'Good aroma.', createdAt: DateTime(2026, 8, 16)),
    ReviewModel(id: 'r17', customerId: 'c7', customerName: 'Bilal Hussain', targetId: 'f1', targetType: 'farmer', rating: 4.8, comment: 'Very organic.', createdAt: DateTime(2026, 8, 17)),
    ReviewModel(id: 'r18', customerId: 'c8', customerName: 'Sara Shah', targetId: 'p18', targetType: 'product', rating: 4.2, comment: 'Fresh ginger.', createdAt: DateTime(2026, 8, 18)),
    ReviewModel(id: 'r19', customerId: 'c9', customerName: 'Omar Farooq', targetId: 'f3', targetType: 'farmer', rating: 4.9, comment: 'Great quality.', createdAt: DateTime(2026, 8, 19)),
    ReviewModel(id: 'r20', customerId: 'c10', customerName: 'Sana Javed', targetId: 'p20', targetType: 'product', rating: 4.5, comment: 'Aromatic rice.', createdAt: DateTime(2026, 8, 20)),
  ];

  static List<CartItemModel> get seedCartItems => [
    CartItemModel(product: seedProducts[0], quantity: 2),
  ];
}
